---
- name: Configure passwordless sudo
  hosts: homelab
  become: true

  tasks:
    - name: Configure passwordless sudo for the user
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/99-{{ ansible_user }}"
        create: true
        owner: root
        group: root
        mode: "0440"
        line: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s